import '../sass/bootstrap.scss';
import '../sass/bootstrap-theme.scss';
import '../bower_components/animate.css/animate.css';
import '../bower_components/angularjs-toaster/toaster.min.css';
import '../includes/index.css';
import '../bower_components/webrtc-adapter/release/adapter_no_edge.js';
import _ from 'underscore';
import 'bootstrap';
import angular from 'angular';
import 'angular-animate';
import 'angular-bootstrap';
import 'angular-md5';
import 'angular-sanitize';
import 'angular-ui-router';
import 'ngstorage';
import 'angularjs-toaster';
import 'oclazyload';
import 'angular-base64';
import 'moment';
import '../bower_components/angular-mask/dist/ngMask.js';
import '../bower_components/angular-ui-utils/ui-utils.js'
import '../bower_components/printThis/printThis.js';
import '../bower_components/laydate/laydate.js';
import '../bower_components/laydate/need/laydate.css';
import '../bower_components/laydate/skins/default/laydate.css';
import '../bower_components/ngmodel-format/src/ngmodel.format.js';
import '../bower_components/moment/moment-locales.js';
import '../bower_components/moment/moment-precise-range.js';
//let template = require('../views/access/login.pug');
//let locals = { /* ... */ };
//let html = template(locals);
//console.log(template(locals));
